### ISSUE TITLE
Weird bug - right clicking on either arrow has number increase/decrease forever.

### ISSUE THREAD

**Issue by johndatserakis** [JayeshLab/vue-numeric-input#10]
Small thing I noticed when using - right clicking on either the up or down arrow makes the value increment or decrement forever.

I'm using Chrome - I've also confirmed I see this behavior in the live demo.

**Comment by didkan** [comment]
I'm seeing the same behavior.
Version 1.0.5

**Comment by JayeshLab** [comment]
Fixed in Version 2.0.0
