### ISSUE TITLE
Placeholder not rendering properly in Firefox

### ISSUE THREAD

**Issue by scheinercc** [JayeshLab/vue-numeric-input#2]
Tested with Firefox Nightly and Firefox DevEdition (Beta)
<img width="320" alt="image" src="https://user-images.githubusercontent.com/817856/45585687-d7cbf380-b92b-11e8-83d7-22704dab8d87.png">

**Comment by JayeshLab** [comment]
Thanks for raising the issue. 
I have fixed css issue with firefox, by hiding native spin button on firefox.
