### ISSUE TITLE
entering zero(0) after dot(.) not working

### ISSUE THREAD

**Issue by shermax** [JayeshLab/vue-numeric-input#4]
Hi!

I am facing issue with entering zero after dot(.).

For example:
I have added numeric input as following to my component:

`<vue-numeric-input class="form-control" v-model="data.amount" :controls="false" :precision="2"></vue-numeric-input>`

But when I try to enter 300.01 it is not allowing to input zero after dot(.). Instead dot(.) is cleared when I input zero.

Thanks!

**Comment by shermax** [comment]
Hi @JayeshLab ! 
Thanks for your help!
But I think it is still not working properly... 
I think there is still one minor case to look at... 
For example I accidentally entered 300.02 (instead of 300.01) and I pressed backspace (once) to clear last number(2) and it was set to 300 (dot and zero after dot is cleared/disappeared)...
I think it should be 300.0... 
Could you give some suggestion on this? 
Thanks!

**Comment by alphatero** [comment]
Hi @JayeshLab 
I have the same problem in use too.
And if I set min value like 0.2 then I can't input number after dot.
Could you support that?

**Comment by JayeshLab** [comment]
Fixed
